<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Products extends \Entities\Products implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getProdId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["prodId"];
        }
        $this->__load();
        return parent::getProdId();
    }

    public function setProdBanner($prodBanner)
    {
        $this->__load();
        return parent::setProdBanner($prodBanner);
    }

    public function getProdBanner()
    {
        $this->__load();
        return parent::getProdBanner();
    }

    public function setProdHomeImg($prodHomeImg)
    {
        $this->__load();
        return parent::setProdHomeImg($prodHomeImg);
    }

    public function getProdHomeImg()
    {
        $this->__load();
        return parent::getProdHomeImg();
    }

    public function setProdIsActive($prodIsActive)
    {
        $this->__load();
        return parent::setProdIsActive($prodIsActive);
    }

    public function getProdIsActive()
    {
        $this->__load();
        return parent::getProdIsActive();
    }

    public function setProdOrder($prodOrder)
    {
        $this->__load();
        return parent::setProdOrder($prodOrder);
    }

    public function getProdOrder()
    {
        $this->__load();
        return parent::getProdOrder();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'prodId', 'prodBanner', 'prodHomeImg', 'prodIsActive', 'prodOrder');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}